### ISSUE TITLE
importError: No module named datetime

### ISSUE THREAD

**Issue by balaramadurai** [novoid/Memacs#37]
Hello,
  I totally love the idea of memacs and I have been using it actively for a few months now. Recently, I upgraded to Ubuntu 16.04LTS and then trouble started with the cronjobs.

Here is the error I get:
```
Traceback (most recent call last):
  File "/home/bala/memacs/bin/memacs_ical.py", line 5, in <module>
    from memacs.ical import CalendarMemacs
  File "/home/bala/memacs/local/lib/python2.7/site-packages/memacs/ical.py", line 9, in <module>
      File "/home/bala/memacs/bin/memacs_ical.py", line 5, in <module>
    from memacs.ical import CalendarMemacs
  File "/home/bala/memacs/local/lib/python2.7/site-packages/memacs/ical.py", line 9, in <module>
    from lib.memacs import Memacs
  File "/home/bala/memacs/local/lib/python2.7/site-packages/memacs/lib/memacs.py", line 8, in <module>
from lib.memacs import Memacs
      File "/home/bala/memacs/local/lib/python2.7/site-packages/memacs/lib/memacs.py", line 8, in <module>
from orgwriter import OrgOutputWriter
  File "/home/bala/memacs/local/lib/python2.7/site-packages/memacs/lib/orgwriter.py", line 12, in <module>
    from orgwriter import OrgOutputWriter
      File "/home/bala/memacs/local/lib/python2.7/site-packages/memacs/lib/orgwriter.py", line 12, in <module>
from orgformat import OrgFormat
  File "/home/bala/memacs/local/lib/python2.7/site-packages/memacs/lib/orgformat.py", line 11, in <module>
    from orgformat import OrgFormat
      File "/home/bala/memacs/local/lib/python2.7/site-packages/memacs/lib/orgformat.py", line 11, in <module>
import datetime
    ImportErrorimport datetime
: No module named datetimeImportError
: No module named datetime
```

Thanks

**Comment by novoid** [comment]
Hello balaramadurai!

This is not an issue with Memacs. When you start "python" and type "import datetime" you'll most likely get the same error (without Memacs at all).

This looks like you've got an issue with your Python 2.x installation.

This page might give you some hints on this:
http://askubuntu.com/questions/509283/python-no-module-named-datetime
