### ISSUE TITLE
mumail: ValueError: time data does not match format

### ISSUE THREAD

**Issue by schvabodka-man** [novoid/Memacs#43]
Helo. When running memacs-mumail, i'm getting

ValueError: time data 'Thu 08 Dec 2016 02:33:56 AM EET' does not match format '%c'

and this traceback:

```
Traceback (most recent call last):
     File "/usr/local/lib/python2.7/dist-packages/memacs/lib/memacs.py", line 187, in handle_main
       self._main()
     File "/usr/local/lib/python2.7/dist-packages/memacs/mu.py", line 116, in _main
       timestamp = self.__getTimestamp(datum)
     File "/usr/local/lib/python2.7/dist-packages/memacs/mu.py", line 71, in __getTimestamp
       mail_date = datetime.strptime(time,"%c")
     File "/usr/lib/python2.7/_strptime.py", line 332, in _strptime
       (data_string, format))
   ValueError: time data 'Thu 08 Dec 2016 02:33:56 AM EET' does not match format '%c'
Traceback (most recent call last):
  File "/usr/local/bin/memacs_mumail.py", line 31, in <module>
    memacs.handle_main()
  File "/usr/local/lib/python2.7/dist-packages/memacs/lib/memacs.py", line 187, in handle_main
    self._main()
  File "/usr/local/lib/python2.7/dist-packages/memacs/mu.py", line 116, in _main
    timestamp = self.__getTimestamp(datum)
  File "/usr/local/lib/python2.7/dist-packages/memacs/mu.py", line 71, in __getTimestamp
    mail_date = datetime.strptime(time,"%c")
  File "/usr/lib/python2.7/_strptime.py", line 332, in _strptime
    (data_string, format))
ValueError: time data 'Thu 08 Dec 2016 02:33:56 AM EET' does not match format '%c'
```

It's somehow releated to timestamp format(and how can i change it for memacs) or just a bug?

**Comment by novoid** [comment]
Hi, I am the maintainer of Memacs.

The mumail module was not implemented by me and I am not using mumail or this Memacs module. Please write memacs-mumail@m.stennes.org as stated in https://github.com/novoid/Memacs/blob/master/docs/memacs_mumail.org so that he is able to help you with this issue. I'll close the issue when it is solved.

Thanks!

**Comment by novoid** [comment]
@schvabodka-man I assume this issue is solved. If you do not report back for confirmation, I'll close this issue soon.

**Comment by novoid** [comment]
I assume that this issue was fixed above. If not, please re-open issue and provide further information. Thanks!
