### ISSUE TITLE
memacs_phonecalls_superbackup python3 failure

### ISSUE THREAD

**Issue by ajft** [novoid/Memacs#67]
After an update to my local install of memacs, a couple of the modules aren't working.

/home/xyzzy/src/memacs/bin/memacs_phonecalls_superbackup.py -a --add-to-time-stamps +10 -f /home/xyzzy/Dropbox/memacs/calllogs.xml -o ./calllogs.org_archive
Traceback (most recent call last):
  File "/home/xyzzy/src/memacs/bin/memacs_phonecalls_superbackup.py", line 44, in <module>
    memacs.handle_main()
  File "/home/xyzzy/src/memacs/memacs/lib/memacs.py", line 187, in handle_main
    self._main()
  File "/home/xyzzy/src/memacs/memacs/phonecalls_superbackup.py", line 236, in _main
    self._args.minimum_duration,
  File "/usr/lib/python3.6/xml/sax/__init__.py", line 48, in parseString
    parser.parse(inpsrc)
  File "/usr/lib/python3.6/xml/sax/expatreader.py", line 111, in parse
    xmlreader.IncrementalParser.parse(self, source)
  File "/usr/lib/python3.6/xml/sax/xmlreader.py", line 125, in parse
    self.feed(buffer)
  File "/usr/lib/python3.6/xml/sax/expatreader.py", line 217, in feed
    self._parser.Parse(data, isFinal)
  File "../Modules/pyexpat.c", line 414, in StartElement
  File "/usr/lib/python3.6/xml/sax/expatreader.py", line 333, in start_element
    self._cont_handler.startElement(name, AttributesImpl(attrs))
  File "/home/xyzzy/src/memacs/memacs/phonecalls_superbackup.py", line 131, in startElement
    if call_duration < self._minimum_duration:
TypeError: '<' not supported between instances of 'int' and 'NoneType'

**Comment by novoid** [comment]
Sorry, this was introduced due to the migration to Python 3 and the lack of a unit test for this module.
Would you like to volunteer to think of helping writing at least a very basic unit test? #75 
@DerBeutlin and I am not using superbackup at all ...
