### ISSUE TITLE
Add chromium history

### ISSUE THREAD

**Issue by 11111000000** [novoid/Memacs#71]
Add chromium history

**Comment by novoid** [comment]
Memacs has a module that indexes the Firefox browsing history: https://github.com/novoid/Memacs/blob/master/docs/memacs_firefox_history.org
@11111000000 would like to see a similar module that deals with the Chrome/Chromium browsers and their history data.
Thanks for helping!

**Comment by balaramadurai** [comment]
@novoid, Thank you for developing Memacs. It is really cool!

I added the chrome-history module to this through the PR - https://github.com/novoid/Memacs/pull/79

Please let me know if this works!

Thanks and have a great day!
Bala

**Comment by novoid** [comment]
I installed Chrome and tried it myself and I now get:

```
vk@sherri ~/src/memacs (git)-[master] % PYTHONPATH="${HOME}/src/memacs/memacs:" python3 bin/memacs_chrome.py --file "$HOME/.config/google-chrome/Default/History"
Traceback (most recent call last):
  File "bin/memacs_chrome.py", line 5, in <module>
    from memacs.chrome import Chrome
  File "/home/vk/src/memacs/memacs/chrome.py", line 13, in <module>
    from lib.memacs import Memacs
  File "/home/vk/src/memacs/memacs/lib/memacs.py", line 8, in <module>
    from .orgwriter import OrgOutputWriter
  File "/home/vk/src/memacs/memacs/lib/orgwriter.py", line 11, in <module>
    from .reader import CommonReader
  File "/home/vk/src/memacs/memacs/lib/reader.py", line 7, in <module>
    import csv
  File "/home/vk/src/memacs/memacs/csv.py", line 12, in <module>
    from .lib.orgformat import OrgFormat
SystemError: Parent module '' not loaded, cannot perform relative import
1 vk@sherri ~/src/memacs (git)-[master] %
```

However, my unit tests and other modules are working fine. Does this error only occur at my side?

@balaramadurai What does your command look like?

**Comment by balaramadurai** [comment]
I have created another PR - https://github.com/novoid/Memacs/pull/81

Let's see if this one works. I realized that the python libraries I used were from pip install and hence has python2.7. So, I copied them from the github clone to the python3.6 python libraries. Now, it seems to have been updated.

Thanks and have a great day!
Bala
